openapi: 3.0.0
components:
  schemas:
    CreateResourceModel:
      properties:
        resource:
          type: string
          description: Tipo de recurso
        id:
          type: integer
          description: ID del recurso
    CreateResourceResponseModel:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de éxito de la operación
    GetResourceModel:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de éxito de la operación
        data:
          oneOf:
            - type: array
              description: Lista de recursos obtenidos
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID del recurso
                  resourceType:
                    type: string
                    description: Tipo de recurso
                  data:
                    type: object
                    description: Información del recurso
                    additionalProperties: true
            - type: object
              description: Un solo recurso obtenido
              properties:
                id:
                  type: integer
                  description: ID del recurso
                resourceType:
                  type: string
                  description: Tipo de recurso
                data:
                  type: object
                  description: Información del recurso
                  additionalProperties: true
  securitySchemes: {}
info:
  title: Star Wars API
  description: API para obtener información sobre Star Wars
  version: 1.0.0
paths:
  /get-resource:
    get:
      operationId: getResource
      summary: Obtiene uno o múltiples recursos de Star Wars
      description: >-
        Obtiene la información de un recurso específico o todos los recursos
        existentes en DynamoDB
      parameters:
        - name: resource
          in: query
          description: Tipo de recurso
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: ID del recurso (opcional)
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Status 200 Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetResourceModel"
  /create-resource:
    post:
      operationId: createResource
      summary: Crea un nuevo recurso de Star Wars
      description: Obtiene la información utilizando el API de Star Wars
      responses:
        "201":
          description: Status 201 Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateResourceResponseModel"
